// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://yzgcikeeuqqdmnmngvgm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6Z2Npa2VldXFxZG1ubW5ndmdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4NjA4NzUsImV4cCI6MjA3NDQzNjg3NX0.prcL2KNhslEEJmlP9ggpnFB5yOUeoc0GyvTGRq-cb1k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});