// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hggqrozynnhktrclrhze.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhnZ3Fyb3p5bm5oa3RyY2xyaHplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MjA4MjMsImV4cCI6MjA3NDQ5NjgyM30.DHU99LWYNg0EMvM2uYHtp34XKsEeMjjWvUQ-puQNcAg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});